src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view
from recipes.views import signup_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import welcome
from .views import RecipeListView
from .views import RecipeDetailView
from .views import records
from django.conf import settings
from django.conf.urls.static import static

app_name = "recipes"

urlpatterns = [
    path("", welcome, name="home"),
    path("list/", RecipeListView.as_view(), name="list"),
    path("list/<pk>", RecipeDetailView.as_view(), name="detail"),
    path("search/", records, name="search"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from cloudinary.models import CloudinaryField


class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.IntegerField(default=-1, help_text="in minutes")
    ingredients = models.CharField(max_length=350, default="")
    description = models.TextField()
    difficulty = models.CharField(max_length=20, blank=True)
    pic = models.URLField(default="", blank=True)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"pk": self.pk})

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(", ")
        if self.cooking_time < 30 and len(ingredients) < 7:
            difficulty = "Easy"
        elif self.cooking_time < 30 and len(ingredients) >= 7:
            difficulty = "Medium"
        elif self.cooking_time >= 30 and len(ingredients) < 7:
            difficulty = "Intermediate"
        elif self.cooking_time >= 30 and len(ingredients) >= 7:
            difficulty = "Hard"
        return difficulty

    def __str__(self):
        return str(self.name)

    def image_tag(self):
        if self.pic:
            return mark_safe(
                '<img src="{}" style="max-width: 100px; max-height: 100px;" />'.format(
                    self.pic.url
                )
            )
        else:
            return mark_safe(
                '<img src="{}" style="max-width: 100px; max-height: 100px;" />'.format(
                    "/media/no_picture.png"
                )
            )

    image_tag.short_description = "Image"

src/recipes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

DIFFIC_CHOICES = (
    ("#1", "Easy"),
    ("#2", "Medium"),
    ("#3", "Intermediate"),
    ("#4", "Hard"),
)


class RecipesSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFFIC_CHOICES)


class SignupForm(UserCreationForm):
    email = forms.EmailField(
        label="",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Email Address"}
        ),
    )
    first_name = forms.CharField(
        label="",
        max_length=20,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "First Name"}
        ),
    )
    last_name = forms.CharField(
        label="",
        max_length=25,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Last Name"}
        ),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "Username"
        self.fields["username"].label = ""
        self.fields["username"].help_text = ""

        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["placeholder"] = "Password"
        self.fields["password1"].label = ""
        self.fields["password1"].help_text = ""

        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirm Password"
        self.fields["password2"].label = ""
        self.fields["password2"].help_text = ""

src/recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, RecipesSearchForm
import pandas as pd
from .utils import get_recipename_from_id, get_chart


def welcome(request):
    return render(request, "recipes/recipes_home.html")


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to a success page or any other page
            return redirect("recipes/recipes_home.html")
    else:
        form = SignupForm()
    return render(request, "auth/signup.html", {"form": form})


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipes/main.html"


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/detail.html"


@login_required
def records(request):
    form = RecipesSearchForm(request.POST or None)
    recipe_df = None
    recipe_diff = None
    chart = None
    qs = None
    if request.method == "POST":
        recipe_diff = request.POST.get("recipe_diff")
        chart_type = request.POST.get("chart_type")

        if recipe_diff == "#1":
            recipe_diff = "Easy"
        if recipe_diff == "#2":
            recipe_diff = "Medium"
        if recipe_diff == "#3":
            recipe_diff = "Intermediate"
        if recipe_diff == "#4":
            recipe_diff = "Hard"

        qs = Recipe.objects.all()
        id_searched = []
        for obj in qs:
            diff = obj.calculate_difficulty()
            if diff == recipe_diff:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df, labels=recipe_df["name"].values)

            recipe_df = recipe_df.to_html()

    context = {
        "form": form,
        "recipe_df": recipe_df,
        "recipe_diff": recipe_diff,
        "chart": chart,
        "qs": qs,
    }

    return render(request, "recipes/search.html", context)

src/recipes/templates/recipes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>Recipe App</title>
</head>

<body>
    <header>
        <!-- Navigation bar -->
        <nav>
            <ul class="navbar">
                <li class="nav-item"><a href="{% url 'recipes:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'recipes:list' %}" class="nav-link">Browse Recipes</a></li>
                <li class="nav-item"><a href="{% url 'recipes:search' %}" class="nav-link">Search Recipes</a></li>
                <li class="nav-item"><a href="{% url 'signup' %}" class="nav-link">Signup</a></li>

                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'logout' %}?next={% url 'recipes:list' %}"
                        class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'login' %}" class="login_btn">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer">
        <!-- Add your footer content here -->
        <p>&copy; 2024 Recipe App</p>
    </footer>
</body>

</html>

src/recipes/templates/recipes/detail.html
{% extends 'recipes/base.html' %}

{% block content %}


<div class="detail-container">
    <div class="detail-content">
        <h1>{{ object.name }}</h1>
        <p>{{ object.description }}</p>
        <img src="{{ recipe.pic }}" alt="{{ recipe.name }}" class="recipe-image">
        <p>Cooking Time: {{ object.cooking_time }} minutes</p>
        <p>Ingredients: {{ object.ingredients }}</p>
        <p>Difficulty: {{ object.calculate_difficulty }}</p>
    </div>
</div>

{% endblock %}

src/recipes/templates/recipes/main.html
{% extends 'recipes/base.html' %}

{% block content %}
<div class="recipe-flex-container">
    <div class="recipe-center-div">
        <div class="grid-layout">
            {% for recipe in object_list %}
            <div class="recipes-container">
                <a href="{% url 'recipes:detail' recipe.pk %}" class="recipe-wrapper">
                    <img src="{{ recipe.pic }}" alt="{{ recipe.name }}" class="recipe-image">
                    <div class="recipe-main-holder">
                        <p class="recipe-link">{{ recipe.name }}</p>
                        <span class="recipe-description">{{ recipe.description|truncatechars:30 }}</span>
                    </div>
                </a>
                <div class="top-notch"></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

src/recipes/templates/recipes/recipes_home.html
{% extends 'recipes/base.html' %}

{% block content %}


<div class="home-container">
    <h1>Welcome to the Recipe App</h1>
    <p>Find delicious recipes for every occasion!</p>
</div>
{% endblock %}

src/recipes/templates/recipes/search.html
{% extends 'recipes/base.html' %}

{% block content %}
<form method="post" class="search-container">
    <h1 style="color:cadetblue;">Search Recipes</h1>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_recipe_diff"></label>
        {{ form.recipe_diff }}
    </div>
    <button type="submit" class="btn">Search</button>
</form>

{% if recipe_df %}
<div class="recipe-flex-container">
    <div class="recipe-center-div">
        <div class="grid-layout">
            {% for recipe in qs %}
            <div class="recipes-container">
                <a href="{% url 'recipes:detail' pk=recipe.pk %}" class="recipe-wrapper">
                    <img src="{{ recipe.pic }}" alt="{{ recipe.name }}" class="recipe-image">
                    <div class="recipe-main-holder">
                        <p class="recipe-link">{{ recipe.name }}</p>
                        <span class="recipe-description">{{ recipe.description|truncatechars:30 }}</span>
                    </div>
                </a>
            </div>
            {% empty %}
            <p class="no-recipes">No recipes found.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<p class="no-recipes">No recipes found.</p>
{% endif %}
{% endblock %}